# user
USER_STATUS_LOCKED = 0
USER_STATUS_ACTIVE = 1
USER_ROLE_ADMIN = 1
USER_ROLE_SUPERVISOR = 2
USER_ROLE_STUDENT = 3
MAX_SIZE_AVATAR = 1<<20  # 1 MB
MAX_SIZE_IMAGE = 1<<19  # 512 KB

# class
CLASS_STATUS_DELETED = 0
CLASS_STATUS_ACTIVE = 1

# cheating type:
NO_CHEATING = 0
CHEATING_PERSONS = 1
CHEATING_LAPTOP = 2
CHEATING_MOUSE = 3
CHEATING_KEYBOARD = 4
CHEATING_WRONG_POSE = 5
EXCEPTION_HAPPENED = 6
NO_IMAGE = 7

# db
DB_CHEATINGS_COLLECTION = "cheatings"
DB_CLASSES_COLLECTION = "classes"
DB_USERS_COLLECTION = "users"

# token
TOKEN_EXPIRED_DAYS = 14
